### PR TITLE
#49 fix for google protobuf

### PR DESCRIPTION
**Pull request by willin**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).

# Reference/Link to the issue solved with this PR (if any)

#50 

# Description of the problem

Sended: Protobuf Message Body (Buffer, 210bytes)

Received: (Buffer 304bytes)

# Description of the solution
 

code caused:

https://github.com/Azure/azure-iot-sdk-node/blob/master/device/transport/mqtt/src/mqtt_base.ts#L189

remove `toString()` and tested ok.

### CODE REVIEW

**Comment by pierreca** [comment]
Thanks for submitting this PR - it looks like a good fix but we need to measure its impact first, by running our full end-to-end test suite, as I'm afraid it might be a breaking change for existing customers. if that were the case, we'd need to do something a little bit more convoluted to still enable the use of protobuf.

**Comment by willin** [comment]
i have no idea about how to test...

**Comment by willin** [comment]
```log

> azure-iot-device-mqtt@1.1.14 test /Users/willin/Desktop/azure-iot-sdk-node/device/transport/mqtt
> npm -s run lint && npm -s run build && npm -s run unittest





  MqttBase
    #connect
      ✓ throws if config structure is falsy
      ✓ throws if host is falsy
      ✓ throws if deviceId is falsy
      ✓ throws if sharedAccessSignature is 'null' and x509 options are 'null'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are 'undefined'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"cert":null,"key":"key"}'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"key":"key"}'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"cert":"","key":"key"}'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"cert":"cert","key":null}'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"cert":"cert"}'
      ✓ throws if sharedAccessSignature is 'null' and x509 options are '{"cert":"cert","key":""}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are 'null'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are 'undefined'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"cert":null,"key":"key"}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"key":"key"}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"cert":"","key":"key"}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"cert":"cert","key":null}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"cert":"cert"}'
      ✓ throws if sharedAccessSignature is 'undefined' and x509 options are '{"cert":"cert","key":""}'
      ✓ uses the authentication parameters contained in the config structure (SharedAccessSignature)
      ✓ uses the authentication parameters contained in the config structure (x509)
      ✓ uses mqtts as a protocol by default
      ✓ uses the uri specified by the config object
      ✓ calls the done callback once successfully connected to the server
      ✓ calls the done callback with an error if we get the 'close' event before connect
      ✓ calls the done callback with an error if we get the 'offline' event before connect
      ✓ calls the done callback with an error if we get the 'error' event before connect
      ✓ calls the done callback with an error if we get the 'disconnect' event before connect
      ✓ calls the done callback with an error only and exactly once even if multiple events are received
      ✓ does not throw if the `done` argument is undefined
    #publish
      ✓ throws if message is falsy
      ✓ calls publish on the MQTT library
      ✓ does not subscribe to the error event
      ✓ uses the proper topic format
      ✓ correctly serializes properties on the topic
      ✓ uses a QoS of 1
      ✓ serializes Message.messageId as $.mid on the topic
      ✓ serializes Message.correlationId as $.cid on the topic
      ✓ serializes Message.userId as $.uid on the topic
      ✓ serializes Message.to as $.to on the topic
      ✓ serializes Message.expiryTimeUtc as $.exp on the topic
      ✓ serializes Message.expiryTimeUtc as $.exp on the topic

  Mqtt
    #sendTwinRequest
      ✓ calls publish method on transport
      ✓ does not throw if done is falsy
      ✓ throws if method is falsy
      ✓ throws if method is not a string
      ✓ throws if resource is falsy
      ✓ throws if resource is not a string
      ✓ throws if properties is falsy
      ✓ throws if properties is not an object
      ✓ throws if properties fails to deserialize to a string
      ✓ throws if body is falsy
      ✓ correctly builds properties string
      ✓ calls done after the body has been published
      ✓ uses the correct topic name
      ✓ uses the correct publish parameters
      ✓ calls done with an error on failure
      ✓ returns MessageEnqueued object on success
    #getTwinReceiver
      ✓ throws if done is falsy
      ✓ calls done when complete
      ✓ creates a new twin receiver object
      ✓ only creates one twin receiver object

  MqttReceiver
    #constructor
      ✓ throws if topicMessage is null
      ✓ throws if topicMessage is undefined
      ✓ throws if topicMessage is 
      ✓ throws if topicMessage is 0
      ✓ throws if mqttClient is null
      ✓ throws if mqttClient is undefined
      ✓ throws if mqttClient is 
      ✓ throws if mqttClient is 0
    #events
      #message
        ✓ subscribes to the topic when a listener is added
        ✓ emits a message event with a Message object when there is a listener
        ✓ unsubscribes from the topic when there are no more listeners
        ✓ populates user-defined message properties from the topic
        ✓ populates Message.messageId from the topic
        ✓ populates Message.to from the topic
        ✓ populates Message.expiryTimeUtc from the topic
        ✓ populates Message.correlationId from the topic
        ✓ populates Message.userId from the topic
        ✓ creates a message even if the properties topic segment is empty
      #method
        ✓ subscribes to the method topic when a listener is added
        ✓ does not subscribe twice to the same topic for multiple event registrations
        ✓ emits a method event when a method message is received
        ✓ emits a method event when a method message is received with properties
        ✓ emits a method event when a method message is received with payload and properties
        ✓ unsubscribes from MQTT topic when there are no more listeners

  Mqtt
    #constructor
      ✓ stores config and created transport in member (68ms)
      ✓ accepts an mqttProvider for testing
    #sendMethodResponse
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ throws an Error if response is falsy or is improperly constructed
      ✓ formats MQTT topic with status code
      ✓ calls callback with error when mqtt publish fails
      ✓ calls callback with null when mqtt publish succeeds
      ✓ sets the uri property to 'mqtts://<host>'
    #setOptions
      ✓ throws a ReferenceError if the `options` argument is 'null'
      ✓ throws a ReferenceError if the `options` argument is 'undefined'
      ✓ throws an ArgumentError if the options.cert property is set but the device is using symmetric key authentication
      ✓ updates the existing configuration with new options
      ✓ calls the `done` callback with no arguments when finished
      ✓ doesn't throw if `done` is not passed in the arguments
    #connect
      ✓ calls connect on the transport
      ✓ registers to emit disconnect when close received

  MqttTranslateError
    ✓ creates a properly constructed error
    ✓ converts client disconnecting error
    ✓ converts invalid topic error
    ✓ converts no connection to broker error
    ✓ converts unacceptable protocol version error
    ✓ converts identifier rejected error
    ✓ converts server unavilable error
    ✓ converts bad username or password error
    ✓ converts not authorized error
    ✓ converts unrecognized packet type error
    ✓ returns generic error when strings dont match

  MqttTwinReceiver
    #constructor
      ✓ accepts a config object
      ✓ throws if client is falsy
    response event
      ✓ asynchronously subscribes when  a listener is added
      ✓ unsubscribes when there are no more listeners
      ✓ emits a response event for every message
      ✓ has a parameter with an object with the correct properties
      ✓ parses the topic name correctly
      ✓ ignores messages on invalid topics
    post event
      ✓ asynchronously subscribes when  a listener is added
      ✓ unsubscribes when there are no more listeners
      ✓ emits a response for every message
      ✓ passes the body as a parameter of the event
    error event
      ✓ emits an error if subscribing to response event fails
      ✓ emits an error if subscribing to post event fails
    subscribed event
      ✓ emits a subscribed event after successful subscription to response event
      ✓ emits a subscribed event after successful subscription to post event
      ✓ passes the the word "response" as an event parameter when the response topic is successfully subscribed to
      ✓ passes the the word "post" as an event parameter when the post topic is successfully subscribed to

  MqttWs
    #constructor
      ✓ stores config and created transport in member
      ✓ sets the uri property to 'wss://<host>:443/$iothub/websocket'


  145 passing (145ms)


=============================== Coverage summary ===============================
Statements   : 89.13% ( 459/515 )
Branches     : 76.97% ( 244/317 )
Functions    : 76.53% ( 75/98 )
Lines        : 90.8% ( 454/500 )
================================================================================
```

passed

**Comment by pierreca** [comment]
was merged with https://github.com/Azure/azure-iot-sdk-node/commit/e6fe764ece51341dd6ab0ab63f2588ea4052475c

**Comment by willin** [comment]
@pierreca  u just closed it... not merged

**Comment by pierreca** [comment]
I did because after rebasing and going through our gate a new commit was created with the same change - which is indicated in my comment. the change is in there, with your name on it, if you look at the commit history.

image

**Pull request closed without merging**
