### PR TITLE
Updated file upload sample to reflect current SDK changes.

### PR DESCRIPTION
**Pull request by solidprinciples**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
  - There are no tests for covering samples, so this is not applicable.
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.

# Reference/Link to the issue solved with this PR (if any)
No current issue was being tracked - the current SDK does not contain `StorageURL`, etc.

# Description of the problem
Upload file sample does not work with the current-most SDKs.

# Description of the solution
Updated the upload file sample code to reflect current most SDK changes.

### CODE REVIEW

**Comment by YoDaMa** [comment]
cheers for the PR @solidprinciples

**Comment by anthonyvercolano** [comment]
@solidprinciples I'm going to let @YoDaMa be the judge on this PR, but, would you be able to fix the linting error?

```
> iot-device-samples@0.0.1 lint /home/vsts/work/1/s/device/samples
> jshint --show-non-errors .

upload_to_blob_advanced.js: line 87, col 21, Missing semicolon.
```
And push?

**Pull request merged**
