### PR TITLE
Update Registry service TypeScript sample with Async/Await

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit updates TypeScript service example code to use new
features from TypeScript 2.* including Async/Await support to
simplify flow of asynchronous operation. Updating TS support
allows also to simplify tooling setup with use of NPM @types.

The results and output of the changed source code is the same
as before update.

Instead of using hardcoded connection string the TS version uses
Node environment variable as widely used way of providing sensitive
information on the process start.

# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).

# Description of the problem
The JavaScript Node engine is based on asynchronous event loop. For this reason using complex flow, like here in registry, can results in extensive use of nested callbacks, which makes using SDK code harder for new users

# Description of the solution
The TypeScript 2 allows to use ES2015/ES2017 Async/Await (asynchronous) functions together with Promise based functions using IoT SDK.

Compare callback based version, with clearly visible nested callbacks and unclear execution flow where there is no guaranted execution order for `registry.list` and `registry.create`:
```JavaScript
// List devices
console.log('**listing devices..');
registry.list((err, deviceList) => {
    deviceList.forEach((device) => {
        let key = device.authentication ? device.authentication.symmetricKey.primaryKey : '<no primary key>';
        console.log(device.deviceId + ': ' + key);
    });
});

// Create a new device
let device = new Device();
device.deviceId = 'sample-device-' + Date.now();
console.log('\n**creating device \'' + device.deviceId + '\'');
registry.create(device, printAndContinue('create', () => {
    // Get the newly-create device
    console.log('\n**getting device \'' + device.deviceId + '\'');
    registry.get(device.deviceId, printAndContinue('get', () => {
        // Delete the new device
        console.log('\n**deleting device \'' + device.deviceId + '\'');
        registry.delete(device.deviceId, printAndContinue('delete'));
    }));
}));
```

with this version:
```TypeScript
// listing devices
console.log('**listing devices ...');
try {
    const deviceList: Device[] = await listDevices(registry);
    deviceList.forEach((device: Device) => {
        let key = (device.authentication) ?
            device.authentication.symmetricKey.primaryKey :
            '<no primary key>';
        console.log(`${device.deviceId}:${key}`);
    });
} catch (error) {
    console.log(error);
}
// Create a new device
let device = new Device();
device.deviceId = `sample-device-${Date.now()}`;
console.log(`**creating device ${device.deviceId}`);
try {
    device = await createDevice(registry, device);
    device = await getDevice(registry, device.deviceId);
} catch (error) {
    console.log(error);
}
```

The output from updated version:
```shell
node registry_sample.js 
**listing devices ...
sample-device-1494020150060:M7GZ2n0BeEo0eJd1UI4Bge4kQx5GuJgyXOe0lSkUNS4=
sample-device-1494020275582:YRAsMXPTCICq6joF48wmzQFokBy8svKmW+bnxndjI+I=
myraspberrypi:BeVjKyM+Dhgj2hGo76V4qjB4HWBnZ0s9XIEmAydadSg=
**creating device sample-device-1494022155595
create status: 200 OK
create device info: {"deviceId":"sample-device-1494022155595","generationId":"636296189567763392","etag":"MA==","connectionState":"Disconnected","status":"enabled","statusReason":null,"connectionStateUpdatedTime":"0001-01-01T00:00:00","statusUpdatedTime":"0001-01-01T00:00:00","lastActivityTime":"0001-01-01T00:00:00","cloudToDeviceMessageCount":0,"authentication":{"symmetricKey":{"primaryKey":"GpqHJnPPsV+hrDWxnuIzRyd1vlZC9kb6PcDnHa7+Wdc=","secondaryKey":"ZbhcSSBrWqE/ZPA9mGHom4pkwiENlN37ZsbsRDRKGpQ="},"x509Thumbprint":{"primaryThumbprint":null,"secondaryThumbprint":null},"SymmetricKey":{"primaryKey":"GpqHJnPPsV+hrDWxnuIzRyd1vlZC9kb6PcDnHa7+Wdc=","secondaryKey":"ZbhcSSBrWqE/ZPA9mGHom4pkwiENlN37ZsbsRDRKGpQ="}}}
get status: 200 OK
get device info: {"deviceId":"sample-device-1494022155595","generationId":"636296189567763392","etag":"MA==","connectionState":"Disconnected","status":"enabled","statusReason":null,"connectionStateUpdatedTime":"0001-01-01T00:00:00","statusUpdatedTime":"0001-01-01T00:00:00","lastActivityTime":"0001-01-01T00:00:00","cloudToDeviceMessageCount":0,"authentication":{"symmetricKey":{"primaryKey":"GpqHJnPPsV+hrDWxnuIzRyd1vlZC9kb6PcDnHa7+Wdc=","secondaryKey":"ZbhcSSBrWqE/ZPA9mGHom4pkwiENlN37ZsbsRDRKGpQ="},"x509Thumbprint":{"primaryThumbprint":null,"secondaryThumbprint":null},"SymmetricKey":{"primaryKey":"GpqHJnPPsV+hrDWxnuIzRyd1vlZC9kb6PcDnHa7+Wdc=","secondaryKey":"ZbhcSSBrWqE/ZPA9mGHom4pkwiENlN37ZsbsRDRKGpQ="}}}
```

Thanks!

### CODE REVIEW

**Comment by pierreca** [comment]
Hi @peterblazejewicz and thanks a lot for the PR, it looks great. Maybe a couple of adjustments will be needed as I look at the details of config files and such but overall I like the idea.

The one thing that gives me a pause (and frankly i've been thinking about it for a while but didn't get to act on it) is that with the current API you have to write Promise wrappers around our good old callbacks. ideally, i'd like the SDK to do this for you. something along the lines of "if you provide a callback with act the usual way, if you don't we return a promise you can await on". I'd be curious to hear if you have any experience with that kind of dual-use API and what you'd think of it. if we could get there, then your sample would become even simpler 'cause you wouldn't have to create Promise wrappers.
thoughts?

**Comment by peterblazejewicz** [comment]
@pierceboggan I fully understand your point and agree 100%. Would you be porting existing SDK to be similar Azure Node SDK recent release?
https://github.com/Azure/azure-sdk-for-node/releases/tag/2.0.0-preview-April2017
Implementation sample detail:
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/webSiteManagement2/lib/webSiteManagementClient.js#L2279-L2297

I have no problems with using either way of asynchronous code, including callback based ones. The promise based SDK and/or async/await TS version is simply easier to grasp (I work with a lot of .Net/C# folks at work)

**Comment by pierreca** [comment]
@peterblazejewicz 
Yep, very much like this, and I do agree with you that it's generally easier to have the ability to use async/await and promises.

I've conferred with the rest of the team and we're not going to pull this is because it splits the sample in 2 steps: 
1. wrap the existing APIs
2. use async/await 

and within the context of the limited number of samples that we have, we prefer to keep the consistency of callbacks across all samples for now.

What I would like to do though, because I don't want to lose either the good thinking and associated benefits, is to mention this in the samples readme file, or maybe the wiki associated with the repository, so that folks looking for samples can know that it is possible (we had a similar entry for Promisification of the SDK using bluebird before).

**Comment by pierreca** [comment]
I've added this page on the wiki:
https://github.com/Azure/azure-iot-sdk-node/wiki/Promises

and updated the samples readme. Thanks for the very good feedback!

**Comment by willin** [comment]
https://github.com/Azure/azure-iot-sdk-node/wiki/Promises

too silly to use so

**Pull request closed without merging**
