### PR TITLE
nit: remove dependency full lodash package

### PR DESCRIPTION
**Pull request by vishnureddy17**

### CODE REVIEW

**Review by BertKleewein — APPROVED** [review]
:shipit:

**Comment by YoDaMa** [comment]
@vishnureddy17 want to update this PR?

**Comment by vishnureddy17** [comment]
@YoDaMa Yeah, I have to investigate why this test is failing. Most likely will get to it after Thanksgiving.

**Comment by vishnureddy17** [comment]
Going to close this as `Object.assign()` doesn't exactly replicate the behavior we are looking for.

In case anyone is curious:
```js
const inspect = require('util').inspect;
const merge = require('lodash').merge;

const target1 = {
  foo: 1,
  bar: {
    baz: 2,
    tweedle: {
      dee: 3
    }
  }
};

const target2 = { ...target1 }; // deep copy

const source = {
  bar: {
    tweedle: null
  }
}

console.log(inspect(merge(target1, source)))            // { foo: 1, bar: { baz: 2, tweedle: null } }
console.log(inspect(Object.assign(target2, source))) // { foo: 1, bar: { tweedle: null } }
```

**Pull request closed without merging**
