### PR TITLE
fix typo in TemperatureController telemetry

### PR DESCRIPTION
**Pull request by rido-min**
workingset->workingSet

### CODE REVIEW

**Comment by danhellem** [comment]
@BertKleewein  and @vishnureddy17 this is a PR to check against some tests. Per @rido-min 

> IIRC we were asking all SDK samples to run the certification tests , which should have detect this issue.

**Review by BertKleewein — APPROVED** [review]
:shipit:

**Comment by danhellem** [comment]
@rido-min what do you want us to do with this?

**Comment by rido-min** [comment]
merge it? not sure why the pipeline fails since the change is fairly simple.

**Comment by BertKleewein** [comment]
The gates have been unreliable.  I would be OK bypassing the gate for this change.

**Comment by danhellem** [comment]
Minor typo fix but the build keeps failing. I am going to just use my admin privileges to merge.

**Pull request merged**
