### PR TITLE
Add documentation button to pnp sample

### PR DESCRIPTION
**Pull request by JimacoMS4**
# Checklist
- [x ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).
- [NA ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ NA] I edited the corresponding document in the `devdoc` folder and added or modified requirements.

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

Just adding a documentation button to the PNP sample  that points to https://docs.microsoft.com/en-us/azure/iot-develop/ . Part of documentation effort.

### CODE REVIEW

**Comment by JimacoMS4** [comment]
@timlt Please check out this PR before I send email to Eric. I want to make sure we're on the same page with the following:
- I added image files for **all four** of the doc buttons in their own folder in the existing doc/images folder. 
- You can see how the button renders here: https://github.com/JimacoMS4/azure-iot-sdk-node/tree/add-documentation-button-to-pnp-sample/device/samples/pnp

Thanks,

Jimaco

**Comment by timlt** [comment]
Looks good to go!

**Comment by ericmitt** [comment]
Good for me as well. Thanks

**Review by ericmitt — APPROVED** [review]

**Comment by JimacoMS4** [comment]
#sign-off

**Comment by JimacoMS4** [comment]
@ericmitt I'm not sure what else I need to do here to get this merged (Note I just closed and re-opened the request, so some checks might be in-progress). It's been sitting for several days.

**Comment by JimacoMS4** [comment]
@pierreca @BertKleewein @anthonyvercolano can you please merge or let me know what else needs to be done? I'm not sure what to do to get the tests to complete, but the PR just adds some images for doc support and a button that points back to docs to one of the samples.

**Pull request merged**
