### PR TITLE
fix: #925 added setOption in case of fileUploadClient

### PR DESCRIPTION
**Pull request by abossard**
# Checklist
- [X] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.

# Reference/Link to the issue solved with this PR (if any)
#925 

# Description of the problem
Pass the options also to the file upload client

# Description of the solution
Checked if there is a fileUploadClient in use, and if so, the options are added to it.

### CODE REVIEW

**Comment by YoDaMa** [comment]
thanks for the contribution @abossard! can you please add a test for this condition? 

It would look very similar to the following test in `_blob_upload_client_test.js`, but it would go inside `_device_client_test.js`. It looks like the `describe` block for the setoptions in device client test is at line 463, so you could start there.

```js
  describe('#setOptions', function () {
    /*Tests_SRS_NODE_DEVICE_BLOB_UPLOAD_CLIENT_99_011: [`setOptions` shall set `fileUploadApi` options.]*/
    it('sets file upload API options', function () {
      var fakeOptions = '__FAKE_OPTIONS__';
      var fakeFileUpload = new FakeFileUploadApi();
      var client = new BlobUploadClient(fakeConfig, fakeFileUpload, null);
      client.setOptions(fakeOptions);
      assert.isTrue(fakeFileUpload.setOptions.calledWith(fakeOptions));
    });
  });
```

**Comment by abossard** [comment]
Hi @YoDaMa  thanks for pointing it out. I added the required test.

**Review by anthonyvercolano — APPROVED** [review]
:shipit:

**Pull request merged**
